language: node_js
install:
  - npm install npm@6 --global
  - npm install
  # - npm ci
  # keep the npm cache around to speed up installs
cache:
  directories:
    - "$HOME/.npm"
node_js:
  - 9
script:
  - npm run bootstrap
  - npm run lerna -- exec npm install
  - npm run build
  - npm run lint
  - npm run test
  - cd smoketest
  - npm install
  - npm run build
