language: node_js
install:
  - npm install npm@6 --global
  - npm install
  # - npm ci
  # keep the npm cache around to speed up installs
cache:
  directories:
    - "$HOME/.npm"
node_js:
  - 8
  - 10
script:
  # https://github.com/lerna/lerna/issues/1457
  - npm run bootstrap -- --no-ci
  - npm run lerna -- exec npm install
  - npm run build
  - npm run lint
  - npm run test
  - cd smoketest
  - npm install
  - npm run build
